# Generated by Django 5.0.1 on 2024-02-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_studentdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='uuid',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
