# Generated by Django 5.0.1 on 2024-03-09 12:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0011_studentdetails_roomno_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='occupants_uuid',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None),
        ),
    ]
