# Generated by Django 5.0.1 on 2024-02-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_studentdetails_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='uuid',
            field=models.UUIDField(),
        ),
    ]
